#+ method: GET
#+ summary: Given a standard name (?_std_string), this query returns its available description (if any)
#+ defaults:
#+   - v: http://www.geoscienceontology.org/svo/svl/variable#soil%40medium_rock__volume_fraction

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?label ?description
from <http://ontosoft.isi.edu:3030/modelCatalog-1.3.0/data/mint@isi.edu> 
WHERE {
  ?_v_iri rdfs:label ?label. 
  optional {?_v_iri schema:description ?description.}
}