#+ method: GET
#+ summary: query that retrieves all metadata from a target resource ?_mv
#+ defaults:
#+   - mv: https://w3id.org/okn/i/mint/TOPOFLOW

SELECT ?prop ?value
from <http://ontosoft.isi.edu:3030/modelCatalog-1.3.0/data/mint@isi.edu>
WHERE {
  ?_mv_iri ?prop ?value
}